name: Test
      
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          swift --version
          swift build -v
      - name: Test
        run: swift test -v --parallel