name: Test
      
on:
  push:
    branches: [ develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        swift: ["5.6.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Log Swift Version
        run: swift --version
      - name: Run Tests
        run: swift test -v